### ISSUE TITLE
Fix alignments for images outside of the block editor

### ISSUE THREAD

**Issue by 2ndkauboy** [elmastudio/aino-theme#97]
I really value that the theme is "Gutenberg-first", but there are still some cases, where styles for the old editor are necessary. This can be post types that don't support the block editor (e.g. WooCommerce products) or when using the theme with a lot of existing content. These old blog posts should also align images correctly. Currently the `.alignright` selector does not exists generically and for images only `.wp-block-image .alignright` is available. Adding something like this (and similar for the other alignment classes) could work:

```css
.entry-content img.alignright {
    float: right;
    margin-left: 1em;
}
```
